version: 2
jobs:
    build:
        docker:
            - image: csizsek/jysp:latest
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                name: run tests
                command: rake test:all
