version: 2
jobs:
    build:
        docker:
            - image: csizsek/jysp:latest
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                  name: python linter
                  command: rake test:lint
            - run:
                name: type checks
                command: rake test:type
            - run:
                name: unit tests
                command: rake test:unit
            - run:
                  name: test coverage
                  command: rake test:coverage
